# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_remove_customers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.FileField(blank=True, null=True, upload_to=b'')),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='User_type',
            field=models.IntegerField(blank=True, choices=[(1, b'admin'), (2, b'buyer'), (3, b'manager'), (4, b'Other')], null=True, verbose_name=b'User Type'),
        ),
    ]
